name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Install sqlite3
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Install bundler
      run: |
        gem install bundler
    - name: Bundle install
      run: |
        bundle install --jobs 4 --retry 3
    - name: Rspec
      run: |
        bundle exec rspec
